### ISSUE TITLE
Error when npm install

### ISSUE THREAD

**Issue by tina1998612** [Bonfida/sns-deploy#1]
I got an error when doing `npm i -g @bonfida/sns-deploy` as shown in the screenshot below:
<img width="575" alt="Screen Shot 2021-08-08 at 12 38 28 AM" src="https://user-images.githubusercontent.com/19768276/128607459-5a3e1833-c559-4bf5-9581-65ab98c7b2d6.png">

Thanks!

**Comment by dr497** [comment]
Thanks catching this. It should be fixed now.
