### ISSUE TITLE
Error: failed to get info about account 

### ISSUE THREAD

**Issue by sshmatrix** [Bonfida/sns-deploy#2]
I am trying to search for a name domain that I bought and it has finished the mandatory auction period. I cannot find the name domain on the website anymore and I encounter the following error:

`Error: failed to get info about account <address>: TypeError: Failed to fetch`

where I have replaced the true address with `<address>`. The said `<address>` does show up on the Solana Explorer though.

**Comment by dr497** [comment]
Mind giving the name of the domain and its address?

**Comment by necro-mancer** [comment]
avneet.sol 
AWnUQD5hfrubjtETvrdYJQh9KvP4LFShGmbDiwXJHPPu

**Comment by necro-mancer** [comment]
*waves*

**Comment by dr497** [comment]
https://naming.bonfida.org/#/domain/avneet loads fine on my end. Seems like there might a connection issues between you and the RPC nodes. This can be the case if you use a VPN for instance

**Comment by sshmatrix** [comment]
Cheers, you are right!

**Comment by sshmatrix** [comment]
> https://naming.bonfida.org/#/domain/avneet loads fine on my end. Seems like there might a connection issues between you and the RPC nodes. This can be the case if you use a VPN for instance

Can you please edit the name out for privacy reasons in your reply? Someone squatted on the domain name anyway

**Comment by paulmillr** [comment]
#4 basically the same
