### ISSUE TITLE
The website is unusable and throws errors

### ISSUE THREAD

**Issue by paulmillr** [Bonfida/sns-deploy#4]
The website is unusable through TOR or any VPN. What's the purpose of deploying it to IPFS, if you still connect to garbage sites that output this? Is it to be "decentralized" while not actually being decentralized? Forcing users to reveal their real IP = obvious censorship risk

```
Error Error: failed to get info about account X: Error: 403 : {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."}, "id": "" }
```

Tried many ways of accessing the website, it just throws errors over and over.

**Comment by dr497** [comment]
The error is self explanatory, it's RPC Pool (a Solana RPC node provider) that is blocking VPNs and TOR. This is unrelated to SNS Deploy or the fact of hosting websites on IPFS.

**Comment by paulmillr** [comment]
@dr497 So, find a different RPC Pool. Or add a dropdown that allows to specify custom pool. It is not a user's problem that your site doesn't work with VPN or TOR. It's your problem that you've picked that pool.

**Comment by paulmillr** [comment]
You just need to understand that i'm a simple new user that tries to work with SOL. 

This would happen to *any* newcomer. If the biggest name service doesn't work the way that is common for many users, the users will think SOL (overall) is unfriendly and broken.

Allowing to specify RPC, or using a list of RPCs is how it's done in similar situations in ETH.
